### ISSUE TITLE
Todo: Implement features

### ISSUE THREAD

**Issue by fuerbringer** [fuerbringer/searxbot#1]
Feel free to help with this @Hoi15A 

- [x] Delete previously set instances for a chat.
- [ ] Only allow URLs with running SearX instances.
- [ ] Add Autocomplete.
- [x] Only allow URLs with http(s) or add them if not provided.
- [x] Separate logic into files.
- [ ] Implement image search.
- [x] Make it possible to select how many search results are displayed (with `/searx`)
- [x] Implement default instance
- [x] Make Results' title to clickable links

**Comment by fuerbringer** [comment]
Closing this by splitting it into two separate issues: #6 #7.
